INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0015', 'outpatient', 'Debridement\ \&\ Destruction', 'Level\ III');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0013', 'outpatient', '\ Debridement\ \&\ Destruction', 'Level\ II');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0012', 'outpatient', '\ Debridement\ \&\ Destruction', 'Level\ I');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0270', 'outpatient', '\ Echocardiogram\ Without\ Contrast', 'Level\ III');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0019', 'outpatient', '\ Excision\/\ Biopsy', 'Level\ I');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0690', 'outpatient', '\ Electronic\ Analysis\ of\ Devices', 'Level\ I');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0692', 'outpatient', '\ Electronic\ Analysis\ of\ Devices', 'Level\ II');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0698', 'outpatient', '\ Eye\ Tests\ \&\ Treatments', 'Level\ II');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0369', 'outpatient', '\ Pulmonary\ Tests', 'Level\ III');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0368', 'outpatient', '\ Pulmonary\ Tests', 'Level\ II');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0607', 'outpatient', '\ Hospital\ Clinic\ Visits', 'Level\ 4');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0206', 'outpatient', '\ Nerve\ Injections', 'Level\ II');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0207', 'outpatient', '\ Nerve\ Injections', 'Level\ III');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0204', 'outpatient', '\ Nerve\ Injections', 'Level\ I');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0203', 'outpatient', '\ Nerve\ Injections', 'Level\ IV');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0209', 'outpatient', '\ Extended\ EEG\,\ Sleep\,\ and\ Cardiovascular\ Studies', 'Level\ II');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0265', 'outpatient', '\ Diagnostic\ and\ Screening\ Ultrasound', 'Level\ I');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0020', 'outpatient', '\ Excision\/\ Biopsy', 'Level\ II');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0267', 'outpatient', '\ Diagnostic\ and\ Screening\ Ultrasound', 'Level\ III');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0269', 'outpatient', '\ Echocardiogram\ Without\ Contrast', 'Level\ II');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0078', 'outpatient', '\ Pulmonary\ Treatment', 'Level\ III');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0377', 'outpatient', '\ Cardiac\ Imaging', 'Level\ II');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0073', 'outpatient', '\ Endoscopy\ Upper\ Airway', 'Level\ III');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0606', 'outpatient', '\ Hospital\ Clinic\ Visits', 'Level\ 3');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0074', 'outpatient', '\ Endoscopy\ Upper\ Airway', 'Level\ IV');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0604', 'outpatient', '\ Hospital\ Clinic\ Visits', 'Level\ 1');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0605', 'outpatient', '\ Hospital\ Clinic\ Visits', 'Level\ 2');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0096', 'outpatient', '\ Noninvasive\ Physiologic\ Studies', 'Level\ II');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0608', 'outpatient', '\ Hospital\ Clinic\ Visits', 'Level\ 5');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('0336', 'outpatient', 'Magnetic\ Resonance\ Imaging\ and\ Magnetic\ Resonance\ Angiography\ without\ Contrast', '');
