INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('491', 'inpatient', 'BACK\ \&\ NECK\ PROC\ EXC\ SPINAL\ FUSION', 'W\/O\ CC\/MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('690', 'inpatient', 'KIDNEY\ \&\ URINARY\ TRACT\ INFECTIONS', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('698', 'inpatient', 'OTHER\ KIDNEY\ \&\ URINARY\ TRACT\ DIAGNOSES', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('699', 'inpatient', 'OTHER\ KIDNEY\ \&\ URINARY\ TRACT\ DIAGNOSES', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('281', 'inpatient', 'ACUTE\ MYOCARDIAL\ INFARCTION\,\ DISCHARGED\ ALIVE', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('280', 'inpatient', 'ACUTE\ MYOCARDIAL\ INFARCTION\,\ DISCHARGED\ ALIVE', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('812', 'inpatient', 'RED\ BLOOD\ CELL\ DISORDERS', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('282', 'inpatient', 'ACUTE\ MYOCARDIAL\ INFARCTION\,\ DISCHARGED\ ALIVE', 'W\/O\ CC\/MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('287', 'inpatient', 'CIRCULATORY\ DISORDERS\ EXCEPT\ AMI', 'W\ CARD\ CATH\ W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('286', 'inpatient', 'CIRCULATORY\ DISORDERS\ EXCEPT\ AMI', 'W\ CARD\ CATH\ W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('379', 'inpatient', 'G\.I\.\ HEMORRHAGE', 'W\/O\ CC\/MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('378', 'inpatient', 'G\.I\.\ HEMORRHAGE', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('372', 'inpatient', 'MAJOR\ GASTROINTESTINAL\ DISORDERS\ \&\ PERITONEAL\ INFECTIONS', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('418', 'inpatient', 'LAPAROSCOPIC\ CHOLECYSTECTOMY', 'W\/O\ C\.D\.E\.\ W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('419', 'inpatient', 'LAPAROSCOPIC\ CHOLECYSTECTOMY', 'W\/O\ C\.D\.E\.\ W\/O\ CC\/MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('377', 'inpatient', 'G\.I\.\ HEMORRHAGE', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('291', 'inpatient', 'HEART\ FAILURE\ \&\ SHOCK', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('195', 'inpatient', 'SIMPLE\ PNEUMONIA\ \&\ PLEURISY', 'W\/O\ CC\/MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('194', 'inpatient', 'SIMPLE\ PNEUMONIA\ \&\ PLEURISY', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('310', 'inpatient', 'CARDIAC\ ARRHYTHMIA\ \&\ CONDUCTION\ DISORDERS', 'W\/O\ CC\/MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('191', 'inpatient', 'CHRONIC\ OBSTRUCTIVE\ PULMONARY\ DISEASE', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('190', 'inpatient', 'CHRONIC\ OBSTRUCTIVE\ PULMONARY\ DISEASE', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('193', 'inpatient', 'SIMPLE\ PNEUMONIA\ \&\ PLEURISY', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('192', 'inpatient', 'CHRONIC\ OBSTRUCTIVE\ PULMONARY\ DISEASE', 'W\/O\ CC\/MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('177', 'inpatient', 'RESPIRATORY\ INFECTIONS\ \&\ INFLAMMATIONS', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('391', 'inpatient', 'ESOPHAGITIS\,\ GASTROENT\ \&\ MISC\ DIGEST\ DISORDERS', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('039', 'inpatient', 'EXTRACRANIAL\ PROCEDURES', 'W\/O\ CC\/MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('253', 'inpatient', 'OTHER\ VASCULAR\ PROCEDURES', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('251', 'inpatient', 'PERC\ CARDIOVASC\ PROC\ W\/O\ CORONARY\ ARTERY\ STENT', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('536', 'inpatient', 'FRACTURES\ OF\ HIP\ \&\ PELVIS', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('918', 'inpatient', 'POISONING\ \&\ TOXIC\ EFFECTS\ OF\ DRUGS', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('917', 'inpatient', 'POISONING\ \&\ TOXIC\ EFFECTS\ OF\ DRUGS', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('308', 'inpatient', 'CARDIAC\ ARRHYTHMIA\ \&\ CONDUCTION\ DISORDERS', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('309', 'inpatient', 'CARDIAC\ ARRHYTHMIA\ \&\ CONDUCTION\ DISORDERS', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('300', 'inpatient', 'PERIPHERAL\ VASCULAR\ DISORDERS', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('301', 'inpatient', 'PERIPHERAL\ VASCULAR\ DISORDERS', 'W\/O\ CC\/MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('303', 'inpatient', 'ATHEROSCLEROSIS', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('305', 'inpatient', 'HYPERTENSION', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('244', 'inpatient', 'PERMANENT\ CARDIAC\ PACEMAKER\ IMPLANT', 'W\/O\ CC\/MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('247', 'inpatient', 'PERC\ CARDIOVASC\ PROC\ W\ DRUG', '');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('246', 'inpatient', 'PERC\ CARDIOVASC\ PROC\ W\ DRUG', '');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('243', 'inpatient', 'PERMANENT\ CARDIAC\ PACEMAKER\ IMPLANT', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('389', 'inpatient', 'G\.I\.\ OBSTRUCTION', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('101', 'inpatient', 'SEIZURES', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('249', 'inpatient', 'PERC\ CARDIOVASC\ PROC', 'W\ NON');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('292', 'inpatient', 'HEART\ FAILURE\ \&\ SHOCK', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('293', 'inpatient', 'HEART\ FAILURE\ \&\ SHOCK', 'W\/O\ CC\/MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('641', 'inpatient', 'MISC\ DISORDERS\ OF\ NUTRITION\,METABOLISM\,FLUIDS\/ELECTROLYTES', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('640', 'inpatient', 'MISC\ DISORDERS\ OF\ NUTRITION\,METABOLISM\,FLUIDS\/ELECTROLYTES', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('439', 'inpatient', 'DISORDERS\ OF\ PANCREAS\ EXCEPT\ MALIGNANCY', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('330', 'inpatient', 'MAJOR\ SMALL\ \&\ LARGE\ BOWEL\ PROCEDURES', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('178', 'inpatient', 'RESPIRATORY\ INFECTIONS\ \&\ INFLAMMATIONS', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('252', 'inpatient', 'OTHER\ VASCULAR\ PROCEDURES', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('176', 'inpatient', 'PULMONARY\ EMBOLISM', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('057', 'inpatient', 'DEGENERATIVE\ NERVOUS\ SYSTEM\ DISORDERS', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('254', 'inpatient', 'OTHER\ VASCULAR\ PROCEDURES', 'W\/O\ CC\/MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('885', 'inpatient', 'PSYCHOSES', '');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('853', 'inpatient', 'INFECTIOUS\ \&\ PARASITIC\ DISEASES\ W\ O\.R\.\ PROCEDURE', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('313', 'inpatient', 'CHEST\ PAIN', '');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('312', 'inpatient', 'SYNCOPE\ \&\ COLLAPSE', '');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('189', 'inpatient', 'PULMONARY\ EDEMA\ \&\ RESPIRATORY\ FAILURE', '');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('065', 'inpatient', 'INTRACRANIAL\ HEMORRHAGE\ OR\ CEREBRAL\ INFARCTION', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('064', 'inpatient', 'INTRACRANIAL\ HEMORRHAGE\ OR\ CEREBRAL\ INFARCTION', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('066', 'inpatient', 'INTRACRANIAL\ HEMORRHAGE\ OR\ CEREBRAL\ INFARCTION', 'W\/O\ CC\/MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('069', 'inpatient', 'TRANSIENT\ ISCHEMIA', '');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('563', 'inpatient', 'FX\,\ SPRN\,\ STRN\ \&\ DISL\ EXCEPT\ FEMUR\,\ HIP\,\ PELVIS\ \&\ THIGH', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('460', 'inpatient', 'SPINAL\ FUSION\ EXCEPT\ CERVICAL', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('315', 'inpatient', 'OTHER\ CIRCULATORY\ SYSTEM\ DIAGNOSES', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('811', 'inpatient', 'RED\ BLOOD\ CELL\ DISORDERS', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('314', 'inpatient', 'OTHER\ CIRCULATORY\ SYSTEM\ DIAGNOSES', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('392', 'inpatient', 'ESOPHAGITIS\,\ GASTROENT\ \&\ MISC\ DIGEST\ DISORDERS', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('390', 'inpatient', 'G\.I\.\ OBSTRUCTION', 'W\/O\ CC\/MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('074', 'inpatient', 'CRANIAL\ \&\ PERIPHERAL\ NERVE\ DISORDERS', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('603', 'inpatient', 'CELLULITIS', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('602', 'inpatient', 'CELLULITIS', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('394', 'inpatient', 'OTHER\ DIGESTIVE\ SYSTEM\ DIAGNOSES', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('552', 'inpatient', 'MEDICAL\ BACK\ PROBLEMS', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('238', 'inpatient', 'MAJOR\ CARDIOVASC\ PROCEDURES', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('469', 'inpatient', 'MAJOR\ JOINT\ REPLACEMENT\ OR\ REATTACHMENT\ OF\ LOWER\ EXTREMITY', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('872', 'inpatient', 'SEPTICEMIA\ OR\ SEVERE\ SEPSIS', 'W\/O\ MV\ 96\+\ HOURS\ W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('870', 'inpatient', 'SEPTICEMIA\ OR\ SEVERE\ SEPSIS', 'W\ MV\ 96\+\ HOURS');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('871', 'inpatient', 'SEPTICEMIA\ OR\ SEVERE\ SEPSIS\ ', 'W\/O\ MV\ 96\+\ HOURS\ W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('638', 'inpatient', 'DIABETES', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('329', 'inpatient', 'MAJOR\ SMALL\ \&\ LARGE\ BOWEL\ PROCEDURES', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('203', 'inpatient', 'BRONCHITIS\ \&\ ASTHMA', 'W\/O\ CC\/MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('202', 'inpatient', 'BRONCHITIS\ \&\ ASTHMA', 'W\ CC\/MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('207', 'inpatient', 'RESPIRATORY\ SYSTEM\ DIAGNOSIS', 'W\ VENTILATOR\ SUPPORT\ 96\+\ HOURS');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('897', 'inpatient', 'ALCOHOL\/DRUG\ ABUSE\ OR\ DEPENDENCE', 'W\/O\ REHABILITATION\ THERAPY\ W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('208', 'inpatient', 'RESPIRATORY\ SYSTEM\ DIAGNOSIS', 'W\ VENTILATOR\ SUPPORT\ \<96\ HOURS');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('149', 'inpatient', 'DYSEQUILIBRIUM', '');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('482', 'inpatient', 'HIP\ \&\ FEMUR\ PROCEDURES\ EXCEPT\ MAJOR\ JOINT', 'W\/O\ CC\/MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('481', 'inpatient', 'HIP\ \&\ FEMUR\ PROCEDURES\ EXCEPT\ MAJOR\ JOINT', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('480', 'inpatient', 'HIP\ \&\ FEMUR\ PROCEDURES\ EXCEPT\ MAJOR\ JOINT', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('948', 'inpatient', 'SIGNS\ \&\ SYMPTOMS', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('473', 'inpatient', 'CERVICAL\ SPINAL\ FUSION', 'W\/O\ CC\/MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('470', 'inpatient', 'MAJOR\ JOINT\ REPLACEMENT\ OR\ REATTACHMENT\ OF\ LOWER\ EXTREMITY', 'W\/O\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('689', 'inpatient', 'KIDNEY\ \&\ URINARY\ TRACT\ INFECTIONS', 'W\ MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('684', 'inpatient', 'RENAL\ FAILURE', 'W\/O\ CC\/MCC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('683', 'inpatient', 'RENAL\ FAILURE', 'W\ CC');
INSERT INTO procedures (fed_proc_id, proc_type, name, options) VALUES ('682', 'inpatient', 'RENAL\ FAILURE', 'W\ MCC');
